services:
  agent-server:
    ports:
      - "8000:8000"
  searxng:
    ports:
      - "8080:8080"
  langfuse-worker:
    ports:
      - "3030:3030"
  langfuse-web:
    ports:
      - "3000:3000"
  clickhouse:
    ports:
      - "8123:8123"
      - "9000:9000"
  minio:
    ports:
      - "9090:9000"
      - "9091:9001"
  redis:
    ports:
      - "6379:6379"
  postgres:
    ports:
      - "5432:5432"
  owui:
    ports:
      - "3001:8080"