services:
  as:
    ports:
      - "8000:8000"
    depends_on:
      - pgvector
  langfuse-web:
    ports:
      - "3000:3000"
  owui:
    ports:
      - "3001:8080"
    depends_on:
      - as
  pgvector:
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data

#  searxng:
#    ports:
#      - "8080:8080"
#  langfuse-worker:
#    ports:
#      - "3030:3030"
#  clickhouse:
#    ports:
#      - "8123:8123"
#      - "9000:9000"
#  minio:
#    ports:
#      - "9090:9000"
#      - "9091:9001"
#  redis:
#    ports:
#      - "6379:6379"
#  postgres:
#    ports:
#      - "5432:5432"
