"""empty message

Revision ID: 974743e5d7b3
Revises: f769e14d1ca4
Create Date: 2025-11-03 10:30:25.890943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '974743e5d7b3'
down_revision: Union[str, Sequence[str], None] = 'f769e14d1ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iaitem',
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mediatype', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uploader', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('publicdate', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('addeddate', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scanner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ocr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ocr_parameters', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ocr_module_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ocr_detected_lang', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ocr_detected_lang_conf', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('identifier')
    )
    op.create_table('iasearch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cached_results', sa.Boolean(), nullable=True),
    sa.Column('cached_filtered', sa.Boolean(), nullable=True),
    sa.Column('cached_metadata', sa.Boolean(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iaentrytoconsider',
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['identifier'], ['iaitem.identifier'], ),
    sa.ForeignKeyConstraint(['search_id'], ['iasearch.id'], ),
    sa.PrimaryKeyConstraint('search_id', 'rank')
    )
    op.create_table('iafilteredresult',
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['iasearch.id'], ),
    sa.PrimaryKeyConstraint('search_id', 'rank')
    )
    op.create_table('iaitemcollection',
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('collection', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['identifier'], ['iaitem.identifier'], ),
    sa.PrimaryKeyConstraint('identifier', 'collection')
    )
    op.create_table('iaitemfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('original', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mtime', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('md5', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('crc32', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sha1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['identifier'], ['iaitem.identifier'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier', 'name', name='uq_iaitemfile_identifier_name')
    )
    op.create_index(op.f('ix_iaitemfile_identifier'), 'iaitemfile', ['identifier'], unique=False)
    op.create_table('iaitemsubject',
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['identifier'], ['iaitem.identifier'], ),
    sa.PrimaryKeyConstraint('identifier', 'subject')
    )
    op.create_table('iapdftodownload',
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['identifier'], ['iaitem.identifier'], ),
    sa.ForeignKeyConstraint(['search_id'], ['iasearch.id'], ),
    sa.PrimaryKeyConstraint('search_id', 'identifier', 'file_name')
    )
    op.create_table('iasearchresult',
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['iasearch.id'], ),
    sa.PrimaryKeyConstraint('search_id', 'rank')
    )
    op.create_table('iadownload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=True),
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('manual_id', sa.Integer(), nullable=True),
    sa.Column('target_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bytes_written', sa.Integer(), nullable=True),
    sa.Column('checksum_ok', sa.Boolean(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['identifier'], ['iaitem.identifier'], ),
    sa.ForeignKeyConstraint(['manual_id'], ['manual.id'], ),
    sa.ForeignKeyConstraint(['search_id'], ['iasearch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iadownload_identifier'), 'iadownload', ['identifier'], unique=False)
    op.create_index(op.f('ix_iadownload_manual_id'), 'iadownload', ['manual_id'], unique=False)
    op.create_index(op.f('ix_iadownload_search_id'), 'iadownload', ['search_id'], unique=False)
    op.create_table('manualsource',
    sa.Column('manual_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['identifier', 'file_name'], ['iaitemfile.identifier', 'iaitemfile.name'], name='fk_manualsource_file'),
    sa.ForeignKeyConstraint(['manual_id'], ['manual.id'], ),
    sa.ForeignKeyConstraint(['search_id'], ['iasearch.id'], ),
    sa.PrimaryKeyConstraint('manual_id', 'identifier', 'file_name')
    )
    op.create_index(op.f('ix_manualsource_search_id'), 'manualsource', ['search_id'], unique=False)
    op.create_foreign_key(None, 'game', 'platform', ['platform'], ['id'])
    op.create_foreign_key(None, 'game', 'genre', ['genre'], ['id'])
    op.create_foreign_key(None, 'game', 'publisher', ['publisher'], ['id'])
    op.create_foreign_key(None, 'manual', 'game', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manual', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_index(op.f('ix_manualsource_search_id'), table_name='manualsource')
    op.drop_table('manualsource')
    op.drop_index(op.f('ix_iadownload_search_id'), table_name='iadownload')
    op.drop_index(op.f('ix_iadownload_manual_id'), table_name='iadownload')
    op.drop_index(op.f('ix_iadownload_identifier'), table_name='iadownload')
    op.drop_table('iadownload')
    op.drop_table('iasearchresult')
    op.drop_table('iapdftodownload')
    op.drop_table('iaitemsubject')
    op.drop_index(op.f('ix_iaitemfile_identifier'), table_name='iaitemfile')
    op.drop_table('iaitemfile')
    op.drop_table('iaitemcollection')
    op.drop_table('iafilteredresult')
    op.drop_table('iaentrytoconsider')
    op.drop_table('iasearch')
    op.drop_table('iaitem')
    # ### end Alembic commands ###
