services:
  clickhouse:
    image: ${BASE_IMAGE-xaer.de/}${CLICKHOUSE_IMAGE-clickhouse}:${CLICKHOUSE_VERSION-latest}
    build:
      context: ${INCLUDED_COMPOSED_CONTEXT-./}
      dockerfile: docker/clickhouse/Dockerfile
      args:
        BASE_IMAGE: ${BASE_CLICKHOUSE_IMAGE-clickhouse/clickhouse-server}
        CLICKHOUSE_VERSION: ${CLICKHOUSE_VERSION-latest}
    container_name: clickhouse
    restart: always
    user: "101:101"
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse # CHANGEME
    volumes:
      - langfuse_clickhouse_data:/var/lib/clickhouse
      - langfuse_clickhouse_logs:/var/log/clickhouse-server
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 1s