services:
  minio:
    image: ${BASE_IMAGE-xaer.de/}${MINIO_IMAGE-minio}:${MINIO_VERSION-latest}
    build:
      context: ${INCLUDED_COMPOSED_CONTEXT-./}
      dockerfile: docker/minio/Dockerfile
      args:
        BASE_IMAGE: ${BASE_MINIO_IMAGE-minio/minio}
        MINIO_VERSION: ${MINIO_VERSION-latest}
    container_name: minio
    restart: always
    entrypoint: sh
    # create the 'langfuse' bucket before starting the service
    command: -c 'mkdir -p /data/langfuse && minio server --address ":9000" --console-address ":9001" /data'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniosecret # CHANGEME
    volumes:
      - langfuse_minio_data:/data
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 1s