services:
  owui:
    image: ${BASE_IMAGE-xaer.de/}${OWUI_IMAGE-open-webui}:${OWUI_VERSION-latest}
    build:
      context: ${INCLUDED_COMPOSED_CONTEXT-./}
      dockerfile: docker/owui/Dockerfile
      args:
        BASE_IMAGE: ${BASE_OWUI_IMAGE-ghcr.io/open-webui/open-webui}
        OWUI_VERSION: ${OWUI_VERSION-latest}
    container_name: open-webui
    restart: always
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL-http://host.docker.internal:11434}
    volumes:
      - open-webui:/app/backend/data