services:
  pgvector:
    container_name: pgvector
    build:
      context: ${INCLUDED_COMPOSED_CONTEXT-./}
      dockerfile: docker/pgvector/Dockerfile
    restart: always
    labels:
      resetableDb: "true"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres # CHANGEME
      POSTGRES_DB: postgres
