services:
  postgres:
    container_name: postgres
    image: ${BASE_IMAGE-xaer.de/}${POSTGRES_IMAGE-postgres}:${POSTGRES_VERSION:-latest}
    build:
      context: ${INCLUDED_COMPOSED_CONTEXT-./}
      dockerfile: docker/postgres/Dockerfile
      args:
        BASE_IMAGE: ${BASE_POSTGRES_IMAGE-postgres}
        POSTGRES_VERSION: ${POSTGRES_VERSION:-latest}
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres # CHANGEME
      POSTGRES_DB: postgres
    volumes:
      - langfuse_postgres_data:/var/lib/postgresql/data