services:
  redis:
    image: ${BASE_IMAGE-xaer.de/}${REDIS_IMAGE-redis}:${REDIS_VERSION-7}
    build:
      context: ${INCLUDED_COMPOSED_CONTEXT-./}
      dockerfile: docker/redis/Dockerfile
      args:
        BASE_IMAGE: ${BASE_REDIS_IMAGE-redis}
        REDIS_VERSION: ${REDIS_VERSION-7}
    container_name: redis
    restart: always
    # CHANGEME: row below to secure redis password
    command: >
      --requirepass ${REDIS_AUTH:-myredissecret}
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 10s
      retries: 10